{'application':{'type':'Application',
          'name':'Mobo Control',
    'backgrounds': [
    {'type':'Background',
          'name':'bgControlMobo',
          'title':'Mobo Control Widget',
          'size':(922, 573),

         'components': [

{'type':'StaticText', 
    'name':'StaticTextSpin', 
    'position':(313, 107), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'text':u'Spin:', 
    },

{'type':'ComboBox', 
    'name':'ComboBoxFrqSpin', 
    'position':(343, 99), 
    'size':(64, -1), 
    'items':[u'Hz', u'10Hz', u'100Hz', u'kHz', u'10kHz', u'100kHz', u'MHz'], 
    'stringSelection':u'100Hz', 
    'text':u'100Hz', 
    },

{'type':'StaticText', 
    'name':'StaticTextPCFRead', 
    'position':(439, 258), 
    'size':(11, -1), 
    'backgroundColor':(237, 236, 235, 255), 
    'text':u'XX', 
    },

{'type':'TextField', 
    'name':'wxTextPCFaddr', 
    'position':(433, 174), 
    'size':(27, -1), 
    'text':u'wxTextPCFaddr', 
    },

{'type':'StaticBox', 
    'name':'externalPcf8574', 
    'position':(383, 146), 
    'size':(118, 161), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'External PCF8574', 
    },

{'type':'StaticText', 
    'name':'StaticTextPCFF11', 
    'position':(389, 258), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'text':u'In   hex:', 
    },

{'type':'StaticText', 
    'name':'StaticTextPCFF1', 
    'position':(388, 207), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'text':u'Out hex:', 
    },

{'type':'StaticText', 
    'name':'StaticTextPCFF', 
    'position':(387, 178), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'text':u'I2C addr:', 
    },

{'type':'TextField', 
    'name':'wxTextPCFwrite', 
    'position':(433, 203), 
    'size':(27, -1), 
    'text':u'wxTextPCFwrite', 
    },

{'type':'Button', 
    'name':'PCFButtonRead', 
    'position':(391, 278), 
    'size':(70, 25), 
    'command':'PCFButtonRead', 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'Read', 
    },

{'type':'Button', 
    'name':'PCFButtonWrite', 
    'position':(390, 233), 
    'size':(70, 25), 
    'command':'PCFButtonWrite', 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'Write', 
    },

{'type':'CheckBox', 
    'name':'PCFCheckBox7', 
    'position':(466, 279), 
    'size':(33, -1), 
    'command':'PCFCheckBox7', 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'7', 
    },

{'type':'CheckBox', 
    'name':'PCFCheckBox6', 
    'position':(466, 264), 
    'size':(33, -1), 
    'command':'PCFCheckBox6', 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'6', 
    },

{'type':'CheckBox', 
    'name':'PCFCheckBox5', 
    'position':(466, 249), 
    'size':(33, -1), 
    'command':'PCFCheckBox5', 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'5', 
    },

{'type':'CheckBox', 
    'name':'PCFCheckBox4', 
    'position':(466, 234), 
    'size':(33, -1), 
    'command':'PCFCheckBox4', 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'4', 
    },

{'type':'CheckBox', 
    'name':'PCFCheckBox3', 
    'position':(466, 219), 
    'size':(33, -1), 
    'command':'PCFCheckBox3', 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'3', 
    },

{'type':'CheckBox', 
    'name':'PCFCheckBox2', 
    'position':(466, 204), 
    'size':(33, -1), 
    'command':'PCFCheckBox2', 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'2', 
    },

{'type':'CheckBox', 
    'name':'PCFCheckBox1', 
    'position':(466, 189), 
    'size':(33, -1), 
    'command':'PCFCheckBox1', 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'1', 
    },

{'type':'CheckBox', 
    'name':'PCFCheckBox0', 
    'position':(466, 174), 
    'size':(33, -1), 
    'command':'PCFCheckBox0', 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'0', 
    },

{'type':'StaticText', 
    'name':'stBiasStatus', 
    'position':(353, 229), 
    'backgroundColor':(237, 236, 235, 255), 
    'foregroundColor':(0, 0, 128, 255), 
    'text':u'stBiasStatus', 
    },

{'type':'Button', 
    'name':'btnReset', 
    'position':(545, 538), 
    'size':(75, 25), 
    'command':'btnReset', 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'Reset', 
    },

{'type':'Button', 
    'name':'btnBiasLButton', 
    'position':(346, 172), 
    'size':(20, -1), 
    'command':'btnBiasLButton', 
    'label':u'L', 
    },

{'type':'Button', 
    'name':'btnBiasHButton', 
    'position':(346, 197), 
    'size':(20, -1), 
    'command':'btnBiasHButton', 
    'label':u'H', 
    },

{'type':'Spinner', 
    'name':'biasRawHSpinner', 
    'position':(282, 248), 
    'size':(60, -1), 
    'backgroundColor':(255, 255, 255, 255), 
    'max':254, 
    'min':0, 
    'value':0, 
    },

{'type':'Spinner', 
    'name':'biasRawLSpinner', 
    'position':(282, 223), 
    'size':(60, -1), 
    'backgroundColor':(255, 255, 255, 255), 
    'max':254, 
    'min':0, 
    'value':0, 
    },

{'type':'StaticText', 
    'name':'stBiasRawTextH', 
    'position':(209, 249), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'foregroundColor':(0, 0, 128, 255), 
    'text':u'Bias Raw High:', 
    },

{'type':'StaticText', 
    'name':'stTemp3', 
    'position':(508, 241), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'foregroundColor':(0, 0, 128, 255), 
    'text':u'Fan Off....(C):', 
    },

{'type':'StaticText', 
    'name':'stTemp2', 
    'position':(508, 217), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'foregroundColor':(0, 0, 128, 255), 
    'text':u'Fan On....(C):', 
    },

{'type':'Spinner', 
    'name':'tmpFanOffSpinner', 
    'position':(585, 237), 
    'size':(50, -1), 
    'backgroundColor':(255, 255, 255, 255), 
    'max':127, 
    'min':0, 
    'value':40, 
    },

{'type':'Spinner', 
    'name':'tmpFanOnSpinner', 
    'position':(585, 213), 
    'size':(50, -1), 
    'backgroundColor':(255, 255, 255, 255), 
    'max':127, 
    'min':0, 
    'value':45, 
    },

{'type':'Spinner', 
    'name':'tmpalarmSpinner', 
    'position':(585, 189), 
    'size':(50, -1), 
    'backgroundColor':(255, 255, 255, 255), 
    'max':127, 
    'min':0, 
    'value':55, 
    },

{'type':'StaticText', 
    'name':'stTemp1', 
    'position':(508, 193), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'foregroundColor':(0, 0, 128, 255), 
    'text':u'Tmp Alarm (C):', 
    },

{'type':'StaticBox', 
    'name':'stTemp', 
    'position':(503, 171), 
    'size':(136, 94), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'Temperature settings', 
    },

{'type':'Button', 
    'name':'btnEncButton', 
    'position':(848, 213), 
    'size':(50, 25), 
    'command':'CMD67', 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'Update', 
    },

{'type':'StaticText', 
    'name':'stPCF8574F', 
    'position':(512, 468), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'foregroundColor':(0, 0, 160, 255), 
    'text':u'PCF8574 FAN..:', 
    },

{'type':'TextField', 
    'name':'wxtext8574f', 
    'position':(590, 465), 
    'size':(30, -1), 
    'alignment':'right', 
    'text':u'wxtext8574f', 
    },

{'type':'TextField', 
    'name':'wxtextvalidminPWRtrigger', 
    'position':(856, 412), 
    'size':(40, -1), 
    'alignment':'right', 
    'text':u'wxtextvalidminPWRtrigger', 
    },

{'type':'StaticText', 
    'name':'stvalidminpwrtrigger', 
    'position':(731, 415), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'foregroundColor':(0, 0, 128, 255), 
    'text':u'Valid min PWR trig..(mW):', 
    },

{'type':'StaticText', 
    'name':'stAlarmLatency', 
    'position':(731, 394), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'foregroundColor':(0, 0, 128, 255), 
    'text':u'Alarm Latency...(x10ms):', 
    },

{'type':'StaticText', 
    'name':'stSWRAlarm', 
    'position':(731, 371), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'foregroundColor':(0, 0, 128, 255), 
    'text':u'SWR Alarm...(1.1 - 99.9):', 
    },

{'type':'TextField', 
    'name':'wxtextSWRlatency', 
    'position':(856, 389), 
    'size':(40, -1), 
    'alignment':'right', 
    'text':u'wxtextSWRlatency', 
    },

{'type':'TextField', 
    'name':'wxtextSWRAlarm', 
    'position':(856, 366), 
    'size':(40, -1), 
    'alignment':'right', 
    'text':u'wxtextSWRAlarm', 
    },

{'type':'StaticBox', 
    'name':'StaticBoxI2C', 
    'position':(503, 287), 
    'size':(122, 229), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'I2C Address Control', 
    },

{'type':'Button', 
    'name':'btnI2CButton', 
    'position':(546, 489), 
    'size':(75, 25), 
    'command':'btnI2CButton', 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'Update', 
    },

{'type':'TextField', 
    'name':'wxtextad7991', 
    'position':(590, 441), 
    'size':(30, -1), 
    'alignment':'right', 
    'text':u'wxtextad7991', 
    },

{'type':'TextField', 
    'name':'wxtextad5301', 
    'position':(590, 418), 
    'size':(30, -1), 
    'alignment':'right', 
    'text':u'wxtextad5301', 
    },

{'type':'TextField', 
    'name':'wxtextTMP100', 
    'position':(590, 395), 
    'size':(30, -1), 
    'alignment':'right', 
    'text':u'wxtextTMP100', 
    },

{'type':'TextField', 
    'name':'wxtext8574l2', 
    'position':(590, 372), 
    'size':(30, -1), 
    'alignment':'right', 
    'text':u'wxtext8574l2', 
    },

{'type':'TextField', 
    'name':'wxtext8574l1', 
    'position':(590, 349), 
    'size':(30, -1), 
    'alignment':'right', 
    'text':u'wxtext8574l1', 
    },

{'type':'TextField', 
    'name':'wxtext8574m', 
    'position':(590, 326), 
    'size':(30, -1), 
    'alignment':'right', 
    'text':u'wxtext8574m', 
    },

{'type':'TextField', 
    'name':'wxtextSi570', 
    'position':(590, 303), 
    'size':(30, -1), 
    'alignment':'right', 
    'text':u'wxtextSi570', 
    },

{'type':'StaticText', 
    'name':'stAD7991', 
    'position':(512, 444), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'foregroundColor':(0, 0, 160, 255), 
    'text':u'AD7991 ADC...:', 
    },

{'type':'StaticText', 
    'name':'stAD5301', 
    'position':(512, 421), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'foregroundColor':(0, 0, 160, 255), 
    'text':u'AD5301 DAC...:', 
    },

{'type':'StaticText', 
    'name':'stTMP100', 
    'position':(512, 398), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'foregroundColor':(0, 0, 160, 255), 
    'text':u'TMP100 temp..:', 
    },

{'type':'StaticText', 
    'name':'stPCF8574C', 
    'position':(512, 375), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'foregroundColor':(0, 0, 160, 255), 
    'text':u'PCF8574 LPF2.:', 
    },

{'type':'StaticText', 
    'name':'stPCF8574B', 
    'position':(512, 352), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'foregroundColor':(0, 0, 160, 255), 
    'text':u'PCF8574 LPF1.:', 
    },

{'type':'StaticText', 
    'name':'stPCF8574A', 
    'position':(512, 329), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'foregroundColor':(0, 0, 160, 255), 
    'text':u'PCF8574 Mobo:', 
    },

{'type':'StaticText', 
    'name':'stSi570', 
    'position':(512, 306), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'foregroundColor':(0, 0, 160, 255), 
    'text':u'Si570 VCXO....:', 
    },

{'type':'StaticBox', 
    'name':'readFromFirmware', 
    'position':(14, 522), 
    'size':(175, 43), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'Read From Firmware', 
    },

{'type':'StaticBox', 
    'name':'ConfigurationSaveRestore', 
    'position':(383, 522), 
    'size':(331, 43), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'Configuration Maintenance', 
    },

{'type':'Button', 
    'name':'btnFileSave', 
    'position':(388, 538), 
    'size':(75, 25), 
    'command':'btnFileSave', 
    'default':1, 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'Save', 
    },

{'type':'Button', 
    'name':'btnFileRestore', 
    'position':(466, 538), 
    'size':(75, 25), 
    'command':'btnFileRestore', 
    'default':1, 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'Restore', 
    },

{'type':'StaticText', 
    'name':'StaticText1', 
    'position':(637, 343), 
    'size':(98, 90), 
    'alignment':'center', 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'style': 'bold', 'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 16}, 
    'foregroundColor':(128, 128, 128, 255), 
    'text':u'Mobo Control Widget', 
    },

{'type':'StaticBox', 
    'name':'staticboxFirmware', 
    'position':(726, 479), 
    'size':(175, 86), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'Firmware Control', 
    },

{'type':'StaticText', 
    'name':'FirmwareSdisplay', 
    'position':(805, 500), 
    'size':(87, -1), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'text':u'FirmwareSdisplay', 
    },

{'type':'StaticText', 
    'name':'serialNumber', 
    'position':(733, 499), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'foregroundColor':(0, 0, 160, 255), 
    'text':u'Serial Number:', 
    },

{'type':'StaticText', 
    'name':'FirmwareVdisplay', 
    'position':(805, 520), 
    'size':(87, -1), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'text':u'FirmwareVdisplay', 
    },

{'type':'StaticText', 
    'name':'stFirmwareV', 
    'position':(733, 519), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'foregroundColor':(0, 0, 160, 255), 
    'text':u'Version........:', 
    },

{'type':'StaticBox', 
    'name':'StBoxMeasuredValues', 
    'position':(23, 145), 
    'size':(163, 162), 
    'backgroundColor':(237, 236, 235, 255), 
    },

{'type':'StaticLine', 
    'name':'StaticLine11', 
    'position':(387, 430), 
    'size':(107, -1), 
    'backgroundColor':(237, 236, 235, 255), 
    'layout':'horizontal', 
    },

{'type':'StaticLine', 
    'name':'StaticLine1', 
    'position':(387, 344), 
    'size':(107, -1), 
    'backgroundColor':(237, 236, 235, 255), 
    'layout':'horizontal', 
    },

{'type':'StaticBox', 
    'name':'bpfUpdBox', 
    'position':(383, 304), 
    'size':(111, 211), 
    'backgroundColor':(237, 236, 235, 255), 
    },

{'type':'Button', 
    'name':'btnBPFupdate', 
    'position':(410, 404), 
    'size':(75, 25), 
    'command':'btnBPFupdate', 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'Update', 
    },

{'type':'Button', 
    'name':'btnLPFupdate', 
    'position':(410, 489), 
    'size':(75, 25), 
    'command':'btnLPFupdate', 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'Update', 
    },

{'type':'TextField', 
    'name':'LPFnr', 
    'position':(450, 436), 
    'size':(35, -1), 
    'alignment':'right', 
    'text':u'LPFnr', 
    },

{'type':'StaticText', 
    'name':'stLPFupdate', 
    'position':(390, 440), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'text':u'LPF......:', 
    },

{'type':'TextField', 
    'name':'LPFnr1', 
    'position':(435, 462), 
    'size':(50, -1), 
    'alignment':'right', 
    'text':u'LPFnr1', 
    },

{'type':'StaticText', 
    'name':'stLPFcpupdate', 
    'position':(390, 466), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'text':u'CP (kHz):', 
    },

{'type':'TextField', 
    'name':'BPFnr1', 
    'position':(435, 377), 
    'size':(50, -1), 
    'alignment':'right', 
    'text':u'BPFnr1', 
    },

{'type':'StaticText', 
    'name':'stBPFcpupdate', 
    'position':(390, 380), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'text':u'CP (kHz):', 
    },

{'type':'TextField', 
    'name':'BPFnr', 
    'position':(450, 351), 
    'size':(35, -1), 
    'alignment':'right', 
    'text':u'BPFnr', 
    },

{'type':'StaticText', 
    'name':'stBPFupdate', 
    'position':(390, 356), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'text':u'BPF......:', 
    },

{'type':'StaticBox', 
    'name':'StaticBox1', 
    'position':(512, 86), 
    'size':(125, 82), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    },

{'type':'StaticBox', 
    'name':'stbPowerCalText1', 
    'position':(726, 280), 
    'size':(175, 188), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'Power Meter and SWR Alarm', 
    },

{'type':'StaticBox', 
    'name':'stbBiasCalText', 
    'position':(203, 145), 
    'size':(168, 162), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'Bias Calibration', 
    },

{'type':'StaticText', 
    'name':'stAuthor', 
    'position':(245, 543), 
    'size':(82, 22), 
    'alignment':'center', 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'Arial', 'family': 'sansSerif', 'size': 6}, 
    'foregroundColor':(0, 0, 128, 255), 
    'text':u'V 0.5 2010-05-18 TF3LJ', 
    },

{'type':'Spinner', 
    'name':'biasHighSpinner', 
    'position':(282, 198), 
    'size':(60, -1), 
    'backgroundColor':(255, 255, 255, 255), 
    'max':2540, 
    'min':0, 
    'value':350, 
    },

{'type':'Spinner', 
    'name':'biasLowSpinner', 
    'position':(282, 173), 
    'size':(60, -1), 
    'backgroundColor':(255, 255, 255, 255), 
    'max':1000, 
    'min':0, 
    'value':20, 
    },

{'type':'StaticText', 
    'name':'stBiasRawTextL', 
    'position':(208, 226), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'foregroundColor':(0, 0, 128, 255), 
    'text':u'Bias Raw Low:', 
    },

{'type':'StaticText', 
    'name':'stBiasH', 
    'position':(208, 203), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'foregroundColor':(0, 0, 128, 255), 
    'text':u'Bias High (mA):', 
    },

{'type':'StaticText', 
    'name':'stBiasL', 
    'position':(208, 178), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'foregroundColor':(0, 0, 128, 255), 
    'text':u'Bias Low  (mA):', 
    },

{'type':'StaticText', 
    'name':'stFrequency', 
    'position':(10, 109), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'style': 'bold', 'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 10}, 
    'foregroundColor':(0, 0, 255, 255), 
    'text':u'Frequency', 
    },

{'type':'StaticText', 
    'name':'stSWRgauge', 
    'position':(10, 60), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'style': 'bold', 'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 10}, 
    'foregroundColor':(0, 0, 255, 255), 
    'text':u'SWR', 
    },

{'type':'StaticText', 
    'name':'stPowergauge', 
    'position':(10, 20), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'style': 'bold', 'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 10}, 
    'foregroundColor':(0, 0, 255, 255), 
    'text':u'Power', 
    },

{'type':'StaticText', 
    'name':'Vdisplay', 
    'position':(118, 235), 
    'size':(60, 13), 
    'alignment':'right', 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 10}, 
    'text':u'Vdisplay', 
    },

{'type':'TextField', 
    'name':'wxtextCtrlPEPwin', 
    'position':(871, 343), 
    'size':(25, -1), 
    'alignment':'right', 
    'text':u'wxtextCtrlPEPwin', 
    },

{'type':'TextField', 
    'name':'wxtextCtrlPCal', 
    'position':(856, 320), 
    'size':(40, -1), 
    'alignment':'right', 
    'text':u'wxtextCtrlPCal', 
    },

{'type':'TextField', 
    'name':'wxtextCtrlPScale', 
    'position':(866, 297), 
    'size':(30, -1), 
    'alignment':'right', 
    'text':u'wxtextCtrlPScale', 
    },

{'type':'StaticText', 
    'name':'stPEP', 
    'position':(731, 348), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'foregroundColor':(0, 0, 128, 255), 
    'text':u'PEP Sample window (1-20):', 
    },

{'type':'StaticBox', 
    'name':'stbFrqOpt', 
    'position':(647, 195), 
    'size':(256, 70), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'Bells and Whistles', 
    },

{'type':'TextField', 
    'name':'wxTextCtrlLCDoffs', 
    'position':(814, 239), 
    'size':(30, -1), 
    'text':u'wxTextCtrlLCDoffs', 
    },

{'type':'TextField', 
    'name':'wxTextCtrlRotEnc', 
    'position':(797, 214), 
    'size':(47, -1), 
    'text':u'wxTextCtrlRotEnc', 
    },

{'type':'StaticText', 
    'name':'stLCDoffset', 
    'position':(651, 244), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'foregroundColor':(0, 0, 128, 255), 
    'text':u'LCD frq offset for PSDR-IQ (kHz):', 
    },

{'type':'StaticText', 
    'name':'stRotary', 
    'position':(651, 219), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'foregroundColor':(0, 0, 128, 255), 
    'text':u'Rotary Encoder Resolution..:', 
    },

{'type':'StaticText', 
    'name':'SWRdisplay', 
    'position':(118, 210), 
    'size':(60, 13), 
    'alignment':'right', 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 10}, 
    'text':u'SWRdisplay', 
    },

{'type':'StaticText', 
    'name':'stSWR', 
    'position':(28, 210), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'style': 'bold', 'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 9}, 
    'foregroundColor':(0, 0, 128, 255), 
    'text':u'SWR              :', 
    },

{'type':'StaticText', 
    'name':'diffDisplay', 
    'position':(548, 125), 
    'size':(74, 17), 
    'alignment':'right', 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'text':u'diffDisplay', 
    },

{'type':'StaticText', 
    'name':'stReal', 
    'position':(515, 104), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'foregroundColor':(0, 0, 128, 255), 
    'text':u'Real:', 
    },

{'type':'StaticText', 
    'name':'PRdisplay', 
    'position':(118, 185), 
    'size':(60, 13), 
    'alignment':'right', 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 10}, 
    'text':u'PRdisplay', 
    },

{'type':'StaticText', 
    'name':'PFdisplay', 
    'position':(118, 160), 
    'size':(60, 13), 
    'alignment':'right', 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 10}, 
    'text':u'PFdisplay', 
    },

{'type':'StaticText', 
    'name':'Idisplay', 
    'position':(118, 260), 
    'size':(60, 13), 
    'alignment':'right', 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 10}, 
    'text':u'Idisplay', 
    },

{'type':'StaticText', 
    'name':'stDiff', 
    'position':(516, 125), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'foregroundColor':(0, 0, 128, 255), 
    'text':u'Diff:', 
    },

{'type':'Spinner', 
    'name':'frqRealSpinner', 
    'position':(541, 97), 
    'size':(90, -1), 
    'backgroundColor':(255, 255, 255, 255), 
    'command':'frqRealSpinner', 
    'max':54000000, 
    'min':0, 
    'value':875000, 
    },

{'type':'StaticText', 
    'name':'stHz', 
    'position':(270, 108), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 10}, 
    'text':u'Hz', 
    },

{'type':'Spinner', 
    'name':'frequencySpinner', 
    'position':(100, 98), 
    'size':(164, 34), 
    'backgroundColor':(192, 192, 192, 255), 
    'font':{'style': 'bold', 'faceName': u'Sans', 'family': 'sansSerif', 'size': 15}, 
    'foregroundColor':(128, 0, 0, 255), 
    'max':54000000, 
    'min':0, 
    'value':7020004, 
    },

{'type':'Button', 
    'name':'btnBiasButton', 
    'position':(282, 278), 
    'size':(84, 25), 
    'command':'btnBiasButton', 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'Bias Calibrate', 
    },

{'type':'CheckBox', 
    'name':'PTTon', 
    'position':(208, 283), 
    'size':(69, 17), 
    'command':'PTTon', 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'Key TX', 
    },

{'type':'StaticText', 
    'name':'stCal', 
    'position':(731, 325), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'foregroundColor':(0, 0, 128, 255), 
    'text':u'Cal..............(1-65535):', 
    },

{'type':'StaticText', 
    'name':'stPscale', 
    'position':(731, 302), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'foregroundColor':(0, 0, 128, 255), 
    'text':u'Scale.............(1-50W):', 
    },

{'type':'StaticText', 
    'name':'TMPdisplay', 
    'position':(118, 285), 
    'size':(60, 13), 
    'alignment':'right', 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'style': 'bold', 'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 10}, 
    'text':u'TMPdisplay', 
    },

{'type':'StaticText', 
    'name':'stTemperature', 
    'position':(28, 285), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'style': 'bold', 'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 9}, 
    'foregroundColor':(0, 0, 128, 255), 
    'text':u'Temperature  :', 
    },

{'type':'StaticText', 
    'name':'stPowerREF', 
    'position':(28, 185), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'style': 'bold', 'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 9}, 
    'foregroundColor':(0, 0, 128, 255), 
    'text':u'Power Ref      :', 
    },

{'type':'StaticText', 
    'name':'stPowerFWD', 
    'position':(28, 160), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'style': 'bold', 'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 9}, 
    'foregroundColor':(0, 0, 160, 255), 
    'text':u'Power Fwd     :', 
    },

{'type':'StaticText', 
    'name':'stCurrent', 
    'position':(28, 260), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'style': 'bold', 'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 9}, 
    'foregroundColor':(0, 0, 160, 255), 
    'text':u'PA Current     :', 
    },

{'type':'StaticText', 
    'name':'stVoltage', 
    'position':(28, 235), 
    'backgroundColor':(237, 236, 235, 255), 
    'font':{'style': 'bold', 'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 9}, 
    'foregroundColor':(0, 0, 160, 255), 
    'text':u'Input Voltage  :', 
    },

{'type':'BitmapCanvas', 
    'name':'BitmapCanvasSWR', 
    'position':(69, 55), 
    'size':(568, 35), 
    'backgroundColor':(255, 255, 255, 255), 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    },

{'type':'Image', 
    'name':'Image1', 
    'position':(659, 10), 
    'size':(245, 156), 
    'backgroundColor':(237, 236, 235, 255), 
    'file':'Po_SWR_board_beta.JPG', 
    },

{'type':'Button', 
    'name':'btnPwrButton', 
    'position':(821, 441), 
    'size':(75, 25), 
    'command':'btnPwrButton', 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'Update', 
    },

{'type':'Button', 
    'name':'btnOffsButton', 
    'position':(848, 238), 
    'size':(50, 25), 
    'command':'CMD68', 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'Update', 
    },

{'type':'Button', 
    'name':'btnSi570Calibrate', 
    'position':(541, 140), 
    'size':(91, 25), 
    'command':'btnSi570Calibrate', 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'Si570 Calibrate', 
    },

{'type':'CheckBox', 
    'name':'Repeat', 
    'position':(120, 543), 
    'size':(65, -1), 
    'command':'Repeat', 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'Loop live', 
    },

{'type':'Button', 
    'name':'btnFilters', 
    'position':(387, 317), 
    'size':(100, 25), 
    'command':'btnFilters', 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'All Filters Update', 
    },

{'type':'Button', 
    'name':'btnFactoryReset', 
    'position':(624, 538), 
    'size':(86, 25), 
    'command':'btnFactoryReset', 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'Factory Reset', 
    },

{'type':'Button', 
    'name':'btnStartUSB', 
    'position':(732, 538), 
    'size':(75, 25), 
    'command':'USB', 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'Start USB', 
    },

{'type':'BitmapCanvas', 
    'name':'BitmapCanvasPWR', 
    'position':(70, 10), 
    'size':(567, 35), 
    'backgroundColor':(255, 255, 255, 255), 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    },

{'type':'Button', 
    'name':'btnRefresh', 
    'position':(21, 538), 
    'size':(75, 25), 
    'command':'Refresh', 
    'default':1, 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'Poll', 
    },

{'type':'Button', 
    'name':'btnQuit', 
    'position':(821, 538), 
    'size':(75, 25), 
    'command':'Exit', 
    'font':{'faceName': u'FreeSans', 'family': 'sansSerif', 'size': 8}, 
    'label':u'Quit', 
    },

{'type':'MultiColumnList', 
    'name':'LPFlist', 
    'position':(200, 315), 
    'size':(175, 200), 
    'backgroundColor':(255, 255, 255, 255), 
    'columnHeadings':[u'Filter', 'Crossover (kHz)'], 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    'foregroundColor':(26, 26, 26, 255), 
    'items':[], 
    'maxColumns':2, 
    'rules':1, 
    },

{'type':'MultiColumnList', 
    'name':'BPFlist', 
    'position':(15, 315), 
    'size':(175, 200), 
    'backgroundColor':(255, 255, 255, 255), 
    'columnHeadings':[u'Filter', 'Crossover'], 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    'foregroundColor':(26, 26, 26, 255), 
    'items':[], 
    'maxColumns':2, 
    'rules':1, 
    },

] # end components
} # end background
] # end backgrounds
} }
